# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:zOzAz2uwKgooKntGFzbUfIlId75Uhe3dWOc5h1U61MsWle5d,iv:MSW4ZbNRIx53BzvSwL7xAMmXuq2RnVhXKghZIcRN768=,tag:rqveFZK29uOYB4fJ0/U3ww==,type:str]
  credentials.json: ENC[AES256_GCM,data:IP9m+aaQg2LgioliDkkaVDFBdJB6t3qV+CJ81UqsKZ/PJhruHPutn7NL3RsyzBqmsh2wRsNz6E6saTN5RFPza3egTjAqxr+8gotXlzl2aP4WphdD9REFuB85WNN0jVi0JsUSxDYWA7eHve4OO1ObYpMsBCZR7bN5Wc4kMqOp4brXjPtiCgIVuV4p0e24vyEpF0AxPPYk/Ptome5pJOHfRPRyFPek7UD2dzr9/rcZKw==,iv:O7D11qDXgIP/eke+bBxKYxwdRD0gj5YnCSNGoCnO834=,tag:lX0qSKjNxlPbHwYo0rVw+Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NHZtL1owSkdPL1VENTlI
        QjFWSFQ1SzNGMURsUkhNQmJKK3dyMjNNZEZjCjJRbHVpcXdkRkZvSVgyL0hGR0ZV
        ckx5QmxSMkY5Y0dsSEt6VVVhUVF5RkEKLS0tIEFxYTBIeTlkem16SFM0bXpQRXJp
        U3A2Y0RFc3dHZFcwYWp2Q0hOMUFjaVEKijyy5/lFhkZqy4Rj9gDfMs7UbuDo7b+0
        5wD1vYKmWbzgTZt+2s990PgJqGKZDuhMSwAZTwmtZ3TsNxbl0iGmAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-27T21:32:41Z"
  mac: ENC[AES256_GCM,data:GGJNYJQa7UnP7AQMHYsfhO5PztIuLiig2+AdvtA3XmmqdvxgYb68jSuvvEZXYb1mERORNPmhkLlYsjIB/9lWMJ31giGUpjW5WO8LsUScssXl3dyyD6J+qgH3VUu7SZKGqHSxT9kS9W+hTl2GzeDh/dLdHibLel29AaFQbxntqu8=,iv:FqTB4wiIVG1GuMP6MxOX7kfrhGCQMlRUPOwaeQ6XLf0=,tag:IOtu16NQQQirZ1jtyuQraw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
