# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:5qcr0jq+1JdnFvTnegM3bfj/GmgFDA2rpa28vWPHR64=,iv:TUyPKmg7h0utiIHJnn4tAUMizuS/YTy8tC1nMRGX7wk=,tag:06ufm2LYEGxPE9Tj0C4DyA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UmJWWXZ5UHFlMFN6TG8v
        Nlk4aHltcktBMUYyTWdlc1JkZ0V1WW0ybVg4CkVZTkc2ZG8vSVVrcWRWaFBQQS9j
        c0xycFhWYUYrcUNjR2tPK3MvKzczNDAKLS0tIDhuUDVhcHAzN3l2Z3l1M1pKYmFn
        RllScjdwc1ByQVA2MlFsMk0ybzFMZ1EKR19sLu/hmKGoJ63QSQhKyULB6/Dyeg23
        XhKh8n81OUy6f8tukdGuPHBNj5gg6AFt9fia/npWAI6vzq7W1jK/LA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-17T15:54:55Z"
  mac: ENC[AES256_GCM,data:ytIVkO1PJpMI92AEg79UxmSbHdRxkPXXfQPgGDYa6SEuKV1sv8djtPO9DVZs0amfDbuslmK5mju5Cq4iyli1m5MFg1wbrmcAA/xYudFsqNeL44nH2in1pyvfLJU3x3G2bXlnZzdJk/D9ExwJI1wz6+mH6iLJfO9WDZ3bhWgeAI4=,iv:6INYu3LXvgD+lYxFszVr2aZstX7bYsQG7TiJp/ASNv4=,tag:CRX5sldCPUpc5faF7TFckQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
