# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ssS/LVpfMspjVtAOxZ4tMIUgNn43ZmtYf7+G0zok958lySVJrWxYuA==,iv:9XWn9/aqwMEU9aB2Ml4j3z4vGWhkMDtQwBkIumkJ9Yg=,tag:Ij4yVd9lzPQxmSXiKXi2zw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNzZuanFxK0lleFoxcnYv
        UjBEekZsQWdKTUViL2lkVGt0WDhpWXdmRWhBCnBMRmU3TjhNQmNrejY5TjR4MWcv
        SXV4QitTa3VMclZYL3BxVHc5cVQ4dU0KLS0tIHpvZE5zSndYTGZoTHlBUVdQVE13
        WFYvb05NeDFhZGdPZktubVlLOGQrb0EKtE6tsrrd7Q8UMmSW9vHcfC6+ewPwhfmH
        2jsKgSztiXJPQgT4d3Bxc4pDxgxxg0+lee9NZHKoKlWOqNYUVHnQwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-28T14:12:10Z"
  mac: ENC[AES256_GCM,data:0gK5J0jPd2bwCr1Tf2PV2YOv5wjquwLgJtzh1Yax2mic48n2Usfr96MXCRC33g6gbSZKjeiZKdfEw3LzI+5pW14YyEFNcT4n6jpQJ6EegsVii+4JzsNpqRwH3j8ecAKn/keuoSsHEMo4s2zTQr9JAwZ2gezV+kmkFSCwEZMGL0o=,iv:LWmTrhwl+MkNyzFVP9kGYi3RHNISCmCPpmYfPfZ1mUo=,tag:GY09jdnG+07McMfDU5Wg1w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
