# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:UuhErxxRmnKyeUJtObJmyU8X3VLF+qkRtYfdMP4kwd8e1IQ1v7/QJw==,iv:F/mHCHYNEiEKNyAkv9hljvkQjQVfCVJNRJ8GySRcyNA=,tag:2WwzEkNvMO+rD5UJY5mjKA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxL2Fybm5FUUsvTkt4S2RL
        TitpcmxZenhlb2dXWG5GNXRBRENQUkRFcXpNCnRtL05tMjArN2t6UWhidUkvcHpn
        c05vSUdRUHJVeEdzd2JsUHlCdTBKVEUKLS0tIEhRRjdXNENiNTdyaDBwZU5ScDZ0
        aE5MdlV6VjhUMUh3bXpCMDNCK1BtWDQKgqXdR8F5s7LTmawBumqj86F4eKDJQiVb
        EQnJty2eZir6Mmnn8rs3QWM1epDEhTVj0blFC0gXv+GG2+a+3GzpFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-27T21:32:41Z"
  mac: ENC[AES256_GCM,data:0qVSZ325zcuQzKQ1EJkwHNVmgyiVWLM0BpBctV6q3XAQSgUhAZo8OoU+AoREEqIcy+fB2/XoMqQuvHwWBGMJzkzrI+4B4zdT6R7tDBOf5zlJxcu8mmB3cNVukW3O2HhtMEsD0irbX8n4DyRR2F3tJ73Wtx6qtzC4VMPCDlPBsKI=,iv:cikX+f4U0akZAfCmhTkzyjk14TG+Rx39J3ihy+MdZRQ=,tag:UanxLE+8cNFdPCAefzhu1w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
