# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:aaCnIYTP57sp4qUrYfevYU0T8frzhqIL+IeeUZmC52RVxXmg,iv:UpUPswXOZKPOlBFo5Mx0nyX6ns1IZJHoEv+dKQObACM=,tag:J3/85dI7PnGgVHiImUTFUg==,type:str]
    credentials.json: ENC[AES256_GCM,data:w3kemo+y6lUiod3l3vTEUOutvwiH7NZUvnbU3RGXdHA856A3QBbkdJKPPe54ZoG2LfQbxfjP0s0uncp/rVC8EtbWHEWi5/4xzgCz/aYby8rnCvEEsqvqrj+yVGhWOXmjPB9QTTYqCKYeIL2OICDvV1DrJq3tUMKKvgO0OMpGzsK6Y2PUJetAbTi98mwB+EXkEqHRKD8UfsODEFHn3ZQp8S6uRqx4rSgVDw7f4t1l2w==,iv:PrJ5Uv6nWIyv6h/PUmcztXP0k1b1A5wctmbxPe19TCk=,tag:eCoh0Bw5lhXPqQ9FB0HBWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcnFxVXJobEYzVGlhRU5n
            cWh5dkkwQmpJbTJ2VDNYTjFIQnBicW9ScGl3CmhJWjV5MnlKOVRpOXQ4ZFljekxI
            K1oxQ3pjZm90bktxalhwRyt4YXU1SjQKLS0tIDRtOEQwT1RxWVoxZWZDVFRuQ2dL
            Q09oc2g3YmZ4MEIydGJYQ01KRHp5VmcKCrvRhnvBg+dR5mw9kMTprI8UjaTkigB7
            OuyIL0pd7PHxgMwSx8hum2nAyu6h9clM/hjyZWVQA5YB/J5sIOSZdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T13:39:44Z"
    mac: ENC[AES256_GCM,data:u4ybMKLS5WMfIT3YwEPduhqhyLDdgle20uhjhxRrqxy7yKRQRsQa8CydjMMXi8Tqs2C/qrmonkP/vBbrkLwbwJh+tr0QnJrpe2dHbm1KUnmIIXNTGoHfbKEPIq/1keXxTx6tcQjBDWRmcZoeH/Mlq1ngx8w3M6+bUIso3uhGQq4=,iv:bYMvrNPtAHDlbrZgf6czMDH9wUO6J/oxQxzY4kmsahU=,tag:xV1rSkL0EYR37yryRoWCbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.3
