# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:aaCnIYTP57sp4qUrYfevYU0T8frzhqIL+IeeUZmC52RVxXmg,iv:UpUPswXOZKPOlBFo5Mx0nyX6ns1IZJHoEv+dKQObACM=,tag:J3/85dI7PnGgVHiImUTFUg==,type:str]
  credentials.json: ENC[AES256_GCM,data:L3soNpMTFJJA0NrAO0bJfEDW63BzgyC5IUCWUO5Rj3mvkT13csfV6lFxRx9EqCYTW6la4WPJdfGMaJmemfBhE1cTdW2Qhj7WrfzDFrtJEkXBjgRGnzeOvxskc/3/Tm3NZJKyhKYA1xehOsbBQCVQut3ujVwzqmzQPSMd7FTx+hVvuqXEIsuCli/wcA0BtmWNmVR4Aj/na1k+2HedAwgzUkAfx2tCmBBMlrLvGz2ASA==,iv:2fI3o4X/Z62txEH+xNTSImjI2n7TB5TlBpgH8+x5Qns=,tag:AJTZuFdWCM4G8f8ZB8kt+A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcnFxVXJobEYzVGlhRU5n
        cWh5dkkwQmpJbTJ2VDNYTjFIQnBicW9ScGl3CmhJWjV5MnlKOVRpOXQ4ZFljekxI
        K1oxQ3pjZm90bktxalhwRyt4YXU1SjQKLS0tIDRtOEQwT1RxWVoxZWZDVFRuQ2dL
        Q09oc2g3YmZ4MEIydGJYQ01KRHp5VmcKCrvRhnvBg+dR5mw9kMTprI8UjaTkigB7
        OuyIL0pd7PHxgMwSx8hum2nAyu6h9clM/hjyZWVQA5YB/J5sIOSZdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-17T12:23:21Z"
  mac: ENC[AES256_GCM,data:rfDz338dUgQM4dgMgBahvcIxRc+yvDHhe2TybLIlSOq3txJbAeE85NovgX3Ytgzt6NlKQhz5cGDHHz8UUJFvVz/3Ym5FuTZL/6QK7nisCv7W5+4RBzupShjr5ssr4oT+Ky9F0EvOFXiGVn1nW35uwSFQUDBtKqmuWpz5TixbgzM=,iv:+gOW1Y4reGpf2zXU/Db773SNeIVMj3WLiAECEAUE21I=,tag:sqCxmNqtn7OtqWFdXLsT2w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
