# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:ifhBZ3oifNquTYOV0pb5PoSQWke2AhhXabzDAF7ae/Ry3mvt,iv:G2TBqErfpCLuyoY4W8sUcYEGZ/YbejPOeE2O2ehOB9k=,tag:Rs5LKMFGYy/7TEBL570Ozg==,type:str]
  credentials.json: ENC[AES256_GCM,data:um9aUAFCTLMhh9YkGhdJCHhqW5Tq5vtvPk917evGz0Hj/V3fwNYXAooMW8CUcTYuQF8l+IipXbo1Ml2zQ/W5oCPgvBqLsISamYlgB4SKDNujZxTRtCGyUImVYQVgmWsuZCCf5bQx17ujYrtT+I5MRW8vVLvKY7Ts3cEbiTeYVygsh182J6wmLA1sqwr5otsdexV/LTjsvUnoS5DFf9xY1EukzHu/HY06pj0Px8/HJw==,iv:PNNFlt3o4sHiSE4h7fL02SEDhNph7s4MDegXnk1VHrU=,tag:xMT/P4+eniekWmWnqaYPoA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWEw4VlB1azBxU1ZFMWto
        V1oyams2VkQzNVRiWFRvdE50QnYwOUI2MEF3Ck84YjlkMENtVkNkTXhzRG01UlhU
        MmdONnZYaEExT0JieENzQ1lEekdBbkkKLS0tIDYvMHNzNFVpUjU5VzN3WHh0SDkr
        ZmttZ2hnWHdFV3lRUDhNRW4zZHUxZU0KTab+10TMkd0Bxv1fZf6OU/YJRFpEvXt9
        zeH+Yely4mA2jsBqrxOuWlqEI1ZmfubqDD/Erjo1lk3sWnR5U9dr4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-17T15:54:55Z"
  mac: ENC[AES256_GCM,data:UgkUspslEHKcRLvHugughLXbycIyDn1Eel4N2GxevWnlwFxjCpqSSqyfbLs8hCaVrThtEoOovWFMh5PT8/8+07A2OLOsoXz5+t5IL2lpd+9D6m2gz7/UGsOohAAQFGePSwkOzqd0yfG1o+UZw5b2s408ZyxnFfPMlTS7YXI7cSQ=,iv:gzbQEbJoTHIJYoOqSuhgeNjPPUOhr4/lgWuYPvt+r28=,tag:92vXrHXUIgzT3Uf5III+qw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
