# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:qq5MeeybaT36,iv:1NoyokhESOlEus07J+qJ0ibIIhFvW5h++jQnzzLPob8=,tag:bXVTSmnJZHu5z1sGKC2LKw==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:riRxqAst2/adyBBDw0qFDPg3/fw=,iv:HjENRG4XrkxmxzqjW4y5COoW5sJD6CxTgGInl+MHOPM=,tag:T9L+G++8n2KjAANQcTVyMQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:U9/AKEDWZF9VjS9Gbyd8mVKUWqTOBPEcSMC8x5gRr2cJG4N9,iv:4QyiV7/IUXbnLKJS0V5QYSRuwXNTFnER2P8booSgohE=,tag:TBG0pcXEJsOHZFSZnHO53g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaUNBcDRXbFVURkNGQVUy
        NDBmL0NHQXEzTnpnTU93MzJwSHpnZU9QYUhFCktyQXlnL280cGZtOHBuVXBKT1FL
        VjhTMCs5cGZaSnV1bWRYc0tFNjJyOHMKLS0tIEEwTnpadHpRREZBNm02bGxuNVQr
        cVdmdkF6dk52SEx5UkNEdEJSbXRlakEKmAY96kj5QDzpnWhIOumVuBhpg0oW3v0h
        f8oDJenebHkBbApIg6DjKnWiRDS6rpvh2gNFXzADxbkCyvArXl8nfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-17T15:54:55Z"
  mac: ENC[AES256_GCM,data:/Xed1PaahUguR/OF1Tsfj4PTQ8Dh9mRUR9C2vy9v3gIpkEpfSq1Eh0BZGIY4LfJx/X7Rx1QtgnD0idnAouGnGDzFhSwVIZDTXxIl0fRSUwNt9kYaxrPBSf5J7SGLSN0pEqVC3MO6+h/1N1GN5kMxsc0oz+b7XLc92FV8vb+TXG8=,iv:X66LK8mNvDLDIOWNKpTGKkH+ZJ/XBjdPLaJRhAcmQKU=,tag:dNcDbRr9zhGx7Dy5D4bx/g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
