# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:edom4CgiO0Eq,iv:q3VF3uDtQtm6zXfd8QmQOv1uRO88is9mumNtIBEnEi4=,tag:lPs39+e/qu5DXnVx9LUakw==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ouZWFrDzOR9caBbS6wyVmHmedpo=,iv:8MxwtkPorpH7XgFduHZabJ9Be9M5SYKNw14H758hQWw=,tag:yAXYDd9JYY8NcSjnvjaE/g==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:tGGZolKYpMJCMJ4E/6Vq2dsmud1SH6t6tR/gRjQr8XMQnr/D,iv:VmS3knzNTuK6stF7ncmZspFjp/VOaTeBhgKz5U1l5qk=,tag:XvY1wgg5krRoZPa7gDuuiQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQXRoa0tGS2NtS2xmblVZ
        dTl3d2prbHNaMEdyaU50TXdtSEF5OGllNFVRCk5HSXpVMFNsOGRtNjRqZitCTmhq
        dEhGc1JTcGpQanBQSDV5ZmJxVHpydU0KLS0tIDhZbHZhUGxKRFNJUXpXTlQwSG43
        MkIyNEZWNW5LTzVQd3MxcVJQQjN0MVUKtswrrSMzq+Awtl1OasyitrfIm4cjdTlk
        uPv++uwa9jXHN9Gru6tJhFOeJJOkwPN3Yec3LILFR/rQ7vxN/q4R7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-23T11:45:15Z"
  mac: ENC[AES256_GCM,data:cUF5UvVIuXbu9dedjpnmgSYg5NQbFlbG/61YEqqvUpokGFcEJvIvzIrRwqwu/0LA7YDm77lEw1QBENCb+5+pRhL3ZbMVXfcSG7c2UL6SMAa4W+fjjNqpIbfQaMQkAOekAz7dwynqQEveEpe2R9rX2HrIaYdNqivcPf0Hze8iBko=,iv:GJLUaWsP11egYBk1P5wE+j8oW/kkGaqcRCjkVZ7h/mA=,tag:wsdRahI0KzEAY+3XpDzKVA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
