# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:BQFCfJpLikkG,iv:TZduLPZV/UueNP7Ii7mxXdiKuMdG6EGft3+24aup1yM=,tag:iJne/ijr15RXv2t6CcHiGA==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:U0cnAq1kU5byn17mVghwMpR8SPw=,iv:5ZQOtasiAl3rw0ELpmzuNntmlBJ87SYJ+L113yV5mp8=,tag:0aZAPcRTPdwm4UJ1PKe5dA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Qtptt/xzy6aEah0BbSNCup7T2RmpbNSi7W3fwvzFAg825/Kk,iv:wVURECyXtHcjdNOIOrHK3allzSK8mj0vcaoFOGjBBlg=,tag:PqAPmawi5aQ6DPryTmjqTQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQzN0VlkxR3NjWnRNemM3
        ckIyUzRzdUsrN3NSTExSWGErNkpHQlVTY2hnCnpwTVZDYVRMcUxjOTZYdmZuL25M
        RFhaWi8vaFBPelc3NldQU0R4K0RiNlkKLS0tIHhCQjVEVWhUZ0JoS3N3SklpTWxZ
        RFFnVnFlV2RLMlVEbmJpOVNQUWJQcVkKa6MB892bJglmBgsVXMP04jq6BLpEydhr
        iHeAddgLEPtxoFCB1nHl0yvT5D9gJZpTwmnu/FrU6gN8hanvJhyJFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-28T14:12:10Z"
  mac: ENC[AES256_GCM,data:dWVJNg1tvEGneEGlocwIZp29y1+Z0g6MGhvBMDG4cBfcwreiMCrFUcS5kKIkOSzBkQQHRp2e7auP2+eYR2JU6rWL5rkYnuCdyUkfxBpoXVYY84wXbUzaqkI2MWepWrAl4Jxyp/CKlqV70fIN8TfDPcis0owFxR0qATSE9jiBltY=,iv:A8Atnk8HpMIGdhqsYf+WFek75l6kXHJ8mCEc3KtPo4E=,tag:9cIDbzawzdusn5kg+weuLA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
