# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:OW29g3W+sBffuHFeUGJT3hgMVSUXPXLeIdrnrSNs4iuYR/VuoNbQwg==,iv:oFNGWGnJqBd+5528ztU27WKlU9NEEJQMnesX4BWiDpI=,tag:swIhAKCqhxz1FdeM2vgEkA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ1gwampWQVdSYnVad3V0
        U3FkRmUzeDFDdWZxRXQxNDRobmxjeHo1QWhRCkk2MnlqbW1CQmg4ZDhQTnBjNVJu
        dVZZY3cvVjhaNVcyMUNmNnF1bHE1dGcKLS0tIEhVRzQ0aUsvVGVLdUhqaTRYbUM4
        Z3JkbE4yOHU0d251YUwwSE5hbHZkNDgKR3pd7j6B00iMKGO7xGJSYm0/v1k962G/
        sJZUzM6GVNOIkzliJzw5UiGkk6wIH57KzBrBDEZK90VFrabs7wNugA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-28T14:12:10Z"
  mac: ENC[AES256_GCM,data:RzzsOYFZGghfoRuSAO2XrQRXMYkXI1r+dMJFwvgPTrsLqOrhJgXtC3hIPKPefQ7jul/HfdJebgmyMcgs9M3OMVQN3D51xSuNUJEwUFIWks5cZSf60E62BoJDXmZ+zUG151qmf3XfOajO9IgclQHu6hsXSCNphsjMkZgMDvu+GHM=,iv:EWnG3pgVbsve3DaFAHmawzcSQNtrY1u/hoC4Byd75fU=,tag:h93HklCIG6BEUAoNcCHhDQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
