# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:cme7A+6hJ8vdh1fbdRQct/xR8VOEw7XWtKcSLviMuYzvZCc5BAAtlg==,iv:AUxfjYvILN0v9IQCfqOlTt6vpg5lly2qbTf4iBjCPHI=,tag:YonQ3qlivyzP1K0UduSa3w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdFYrNmZ4dkR2cFQ1U0hp
        RnAxdGhKditmamRES1ROMysrQ0RXNDB5U240CkVFZkpJcWY2cHdZdnMveStIY1ZE
        NDAwUjRrREs1NUFXQXBZS3NWZjhjYkEKLS0tIGljTWxTdkRkdHlOeXpBRTE4UWl3
        UkFOcE11ZWV1WnVKVnNTRzFBbkFKTFUK3zUA/l68oiFSwzzRJnlrdvhaS49Iuj8G
        DRmlXiwZRdsOp5G1tcR5K4KscoXMRUOVZe/z14a6IXDluzczen3UaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-17T12:23:21Z"
  mac: ENC[AES256_GCM,data:mMLz1ucguzUiJMhWVg9t6gwn0SgWvVlx+yFZh6lV/p7MWE8ufa5/f9/GQ8+/kC27aRkv23TSLdu3+ME+/v3Traf0qdz/CCrL+pjJBvk4OoikrrdHixYO1R8ZoDyXwxlt2tQy8uBkUxZaIwK2ixb4d62w2SSxHf807LAJMinRlaw=,iv:QPhoajfWQugXiUm28/SZg4c814Kg+RcZi4AxegYaJpc=,tag:4E7gkfwZxoR/lNjJP5Xy/Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
