# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:YVu2WmRAIPhpWSWYTxuB7zWVadbUBo/NgHGZuh3wYe8LRPTbXh3nPA==,iv:hwnX4AgtSifZr62ltA/won9snMSIvcSXWBke3SIQyPk=,tag:ufSJEKa86D2CLoXoD+/CQQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WXZhalVGbHJXT2NQZ242
        MVRoaWdsODNpZnp4NUdmOUZieFYrWTNiNkZBCmlUOTVMaTJ3U29KZ2ZlVkpnZEpr
        SkJMWDQxaW9HbE9nODl5THQwb0R3M1kKLS0tIHl0SUJTck9jUDFXUHRrT1NoSEo1
        VGRsVW14K2pXWWhqSVc5TDVGTUY2VVUKCv1VTKeVDBrstEeKEj2t76Ju0lCII1mT
        lSugcTF8i+bbUaDd2ZJXV9/yvHG1pCdqiOlhxZ2kTt5RtLtd99FhTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-23T11:45:15Z"
  mac: ENC[AES256_GCM,data:Sl2/gUr6S7K0f3wS6E5730nu7/KNSeUaJ2ABN3izoRRhYhP3KkE+1xNkdpm7wyL+/T8ufQa6kq3uKMGkRsktp98lASL4ShNVuitzFfMPk3Yb3Vd447h9qPl1GFPGgGIsdrGS0CZqX5iOoRxYrPJxCNuxxLF29nyZnVFZCHZPNWQ=,iv:MF+YIwiq2f0S8NJNcFxqSniTMm/9xRi1eClJz7tb2aI=,tag:Keh37RnDnlEz+NXKwJzLfA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
