# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:9DommDvAiVBeXYM5NE/kfsvFO/2t1i/n0+2u0ihhFuTkHB2uREgbNQ==,iv:eT2+/Ia2nHU2ZjLCk5dZ8V/2EsEDJqZEN828pE7pOCg=,tag:YUrPjTeXRtmby9AqYhJjxw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZm0xaENhVG1FbDhCcEtV
        aytwSFRsdkh2bmF6eUsweHc1RXEwTFpSY1dZCmpkU2pHb01BejVIUGVaZG5zMXow
        YWdWM2F6TGdqUVYvMnBkZDFkSW1lUDAKLS0tIFViRmdEdTlnZVRoOWpsYzhIWThm
        Q205S25KRi9rVWw2SzJIckRMZERwMTQKuBDPVmId90lXth7kUnsjZAgwKGUr+8Hr
        YJviAHucCLkQue8cuXSfqgPPmdIgGz/F7IQnXq8aGDevTwjPVJrCtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-17T15:54:55Z"
  mac: ENC[AES256_GCM,data:f+uJddYFVE0El1GhAEBIIlF2fLZslMi0Dt3dYPbR9lpRo9E/qk8pHfgnw3VFigA4oVDM7dcG05mODFPP7/Y/khi+zsyuTwoW5EMeJD5BhBK0RjY29H3Jw5yB+Vn7doNVnNij5ky9rpnFTPuUi0S/psrRaNfla3ixciAFxKqPQqA=,iv:iU+NH/mC1a2MHikV/8YPFCRiqhRtWyOdLF9g7fUJMP8=,tag:wH/UxPrzPxD/sYHTlTn/+g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
